Add pattern-category (fate#323785)
openSUSE/instsource-susedata pull request #2
Opened 2018-10-30 14:05 UTC by lnussel

2018-10-30 14:18 UTC, mlschroe commented on add_product_susedata
> +    my $i18n_category    = gettext($category) if $category;
This is wrong, you must not use a trailing "if" with a my statement. It does not do what you expect.

2018-10-30 14:20 UTC, mlschroe requested changes
See inline comment

2018-10-30 20:10 UTC, mlschroe commented
I also vind it very strange to have a translated pattern-category in the susedata.lang file but no pattern-category in susedata. Could you please change the code so that the untranslated category is also added?

2018-11-05 12:40 UTC, lnussel commented
done. Note there is another inconsistency, not introduced by me though. The eula tag is without lang tag in in susedata.lang

2018-11-05 12:49 UTC, mlschroe approved these changes

2018-11-05 12:50 UTC, mlschroe commented
Yeah, the eula should also get a lang tag. This needs a change in ABXML::susedata_i18n, though. Anyway, it's a different issue.

2018-11-12 13:21 UTC, lnussel commented
so anyone going to merge this and submit a package?

2018-12-05 14:52 UTC, merged